[program:reparaturcafe]
command=/home/oskar/reparaturcafe/venv/bin/gunicorn -b localhost:8000 -w 4 reparaturcafe:app
directory=/home/oskar/reparaturcafe
user=oskar
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
