"""Added type to Log

Revision ID: 16e074aa3e08
Revises: a489c2ea5f42
Create Date: 2019-09-06 18:08:58.559106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e074aa3e08'
down_revision = 'a489c2ea5f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'type')
    # ### end Alembic commands ###
