"""added FFPing

Revision ID: 4aa814425815
Revises: 90619826bf8e
Create Date: 2019-05-09 13:27:03.003807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa814425815'
down_revision = '90619826bf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ff_ping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ff_ping_timestamp'), 'ff_ping', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ff_ping_timestamp'), table_name='ff_ping')
    op.drop_table('ff_ping')
    # ### end Alembic commands ###
