"""After git revert removed timestamps

Revision ID: 4c2b3deafee1
Revises: b28d82e8c02b
Create Date: 2019-09-05 14:21:53.518085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c2b3deafee1'
down_revision = 'b28d82e8c02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_online_check_timestamp', table_name='online_check')
    op.drop_index('ix_online_check_timestamp_income', table_name='online_check')
    op.drop_column('online_check', 'timestamp')
    op.drop_column('online_check', 'timestamp_income')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('online_check', sa.Column('timestamp_income', mysql.DATETIME(), nullable=True))
    op.add_column('online_check', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_online_check_timestamp_income', 'online_check', ['timestamp_income'], unique=False)
    op.create_index('ix_online_check_timestamp', 'online_check', ['timestamp'], unique=False)
    # ### end Alembic commands ###
