"""Added is_active to attachment

Revision ID: 6f219438e12c
Revises: 1cb01d20979c
Create Date: 2020-02-01 12:15:45.410627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f219438e12c'
down_revision = '1cb01d20979c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'is_active')
    # ### end Alembic commands ###
