"""added log

Revision ID: 90619826bf8e
Revises: af9d3de7eeb8
Create Date: 2019-05-09 06:45:52.303598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90619826bf8e'
down_revision = 'af9d3de7eeb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('online_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('device_issue', sa.String(length=1000), nullable=True),
    sa.Column('device_opened', sa.Boolean(), nullable=True),
    sa.Column('device_manual', sa.Boolean(), nullable=True),
    sa.Column('customer_name', sa.String(length=128), nullable=True),
    sa.Column('customer_email', sa.String(length=128), nullable=True),
    sa.Column('customer_tel', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('online_check_id', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['online_check_id'], ['online_check.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_timestamp'), 'log', ['timestamp'], unique=False)
    op.drop_table('onlinecheck')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onlinecheck',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('device_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('device_issue', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('device_opened', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('device_manual', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('customer_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('customer_email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('customer_tel', mysql.VARCHAR(length=128), nullable=True),
    sa.CheckConstraint('`device_manual` in (0,1)', name='CONSTRAINT_2'),
    sa.CheckConstraint('`device_opened` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_log_timestamp'), table_name='log')
    op.drop_table('log')
    op.drop_table('online_check')
    # ### end Alembic commands ###
