"""First migrate

Revision ID: a65726e803ef
Revises: 
Create Date: 2019-05-09 14:45:44.939676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65726e803ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ff_ping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ff_ping_timestamp'), 'ff_ping', ['timestamp'], unique=False)
    op.create_table('online_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('device_issue', sa.String(length=1000), nullable=True),
    sa.Column('device_opened', sa.Boolean(), nullable=True),
    sa.Column('device_manual', sa.Boolean(), nullable=True),
    sa.Column('customer_name', sa.String(length=128), nullable=True),
    sa.Column('customer_email', sa.String(length=128), nullable=True),
    sa.Column('customer_tel', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_role_desc'), 'role', ['desc'], unique=False)
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('online_check_id', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['online_check_id'], ['online_check.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_timestamp'), 'log', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_log_timestamp'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_role_desc'), table_name='role')
    op.drop_table('role')
    op.drop_table('online_check')
    op.drop_index(op.f('ix_ff_ping_timestamp'), table_name='ff_ping')
    op.drop_table('ff_ping')
    # ### end Alembic commands ###
