"""Added category

Revision ID: ab53f41c5def
Revises: b0b1b0dd6601
Create Date: 2019-04-07 17:11:57.530761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab53f41c5def'
down_revision = 'b0b1b0dd6601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('samples', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
