"""first migrate

Revision ID: af9d3de7eeb8
Revises: 
Create Date: 2019-05-07 11:20:34.299933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af9d3de7eeb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onlinecheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('device_issue', sa.String(length=1000), nullable=True),
    sa.Column('device_opened', sa.Boolean(), nullable=True),
    sa.Column('device_manual', sa.Boolean(), nullable=True),
    sa.Column('customer_name', sa.String(length=128), nullable=True),
    sa.Column('customer_email', sa.String(length=128), nullable=True),
    sa.Column('customer_tel', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('samples', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('onlinecheck')
    # ### end Alembic commands ###
