"""Added timestamps and relationship between User/Onlinecheck

Revision ID: b28d82e8c02b
Revises: 8da37ea5beaf
Create Date: 2019-09-05 14:04:38.499770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28d82e8c02b'
down_revision = '8da37ea5beaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('online_check', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.add_column('online_check', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('online_check', sa.Column('timestamp_income', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_online_check_timestamp'), 'online_check', ['timestamp'], unique=False)
    op.create_index(op.f('ix_online_check_timestamp_income'), 'online_check', ['timestamp_income'], unique=False)
    op.create_foreign_key(None, 'online_check', 'user', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'online_check', type_='foreignkey')
    op.drop_index(op.f('ix_online_check_timestamp_income'), table_name='online_check')
    op.drop_index(op.f('ix_online_check_timestamp'), table_name='online_check')
    op.drop_column('online_check', 'timestamp_income')
    op.drop_column('online_check', 'timestamp')
    op.drop_column('online_check', 'supervisor_id')
    # ### end Alembic commands ###
